GPU = False
DEVICE_INDEX = 0

STATE_DIM = 9
ACTION_DIM = 1
HIDDEN = [8, 4]
MODEL_PATH = 'model/'

BUFFER_SIZE = 1e6
EXPLORATION_EPISODES = 30
MAX_EPISODES = 500
MAX_STEPS = 10000
UPDATE_INTERVAL = 100
BATCH_SIZE = 64

PROCESSOR_COUNT = 8
TASK_PER_PROCESSOR = 5
INSTANCES_PER_TASK = 20

MAX_PERIOD = 30
MIN_PERIOD = 20
MAX_DEADLINE = 30
MIN_DEADLINE = 10
GRANULARITY = 1 / 2
MIN_EXECUTE_TIME = 5
MAX_EXECUTE_TIME = 20
LAMBDA = 100
