GPU = False
DEVICE_INDEX = 0

STATE_DIM = 9
ACTION_DIM = 1
HIDDEN_DIM = [16, 8]
MODEL_PATH = 'model/'

BUFFER_SIZE = 1e6
EXPLORATION_EPISODES = 30
MAX_EPISODES = 500
MAX_STEPS = 10000
UPDATE_INTERVAL = 100
BATCH_SIZE = 64
Q_LEARNING_RATE = 1e-2
POLICY_LEARNING_RATE = 1e-3
DISCOUNT_RATE = 0.95
SOFT_UPDATE_TAU = 1e-3
TARGET_UPDATE_DELAY = 3
UPDATE_REPEAT_COUNT = 3

PROCESSOR_COUNT = 8
TASK_PER_PROCESSOR = 5
INSTANCES_PER_TASK = 20
